/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.com.jaromir.olszewski.mavenproject3;

import java.util.Scanner;

/**
 *
 * @author lawio
 */
public class wlasnyprojekt extends javax.swing.JFrame {

    /**
     * Creates new form wlasnyprojekt
     */
    public wlasnyprojekt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jo_jPanel1 = new javax.swing.JPanel();
        jo_jLabel1 = new javax.swing.JLabel();
        jo_jSlider1 = new javax.swing.JSlider();
        jo_jLabel2 = new javax.swing.JLabel();
        jo_jLabel3 = new javax.swing.JLabel();
        jo_jLabel4 = new javax.swing.JLabel();
        jo_jLabel6 = new javax.swing.JLabel();
        jo_jLabel7 = new javax.swing.JLabel();
        jo_jComboBox1 = new javax.swing.JComboBox<>();
        jo_jLabel8 = new javax.swing.JLabel();
        jo_jToggleButton1 = new javax.swing.JToggleButton();
        jo_jToggleButton2 = new javax.swing.JToggleButton();
        jo_jLabel9 = new javax.swing.JLabel();
        jo_jTextField1 = new javax.swing.JTextField();
        jo_jMenuBar = new javax.swing.JMenuBar();
        jo_jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jo_jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jo_jMenu3 = new javax.swing.JMenu();
        jo_MenuItem7 = new javax.swing.JMenuItem();
        jo_jMenuItem8 = new javax.swing.JMenuItem();

        jLabel5.setBackground(new java.awt.Color(255, 255, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("trudny");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gra komputerowa");

        jo_jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jo_jPanel1.setForeground(new java.awt.Color(51, 51, 255));

        jo_jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jo_jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jo_jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jo_jLabel1.setText("łatwy");

        jo_jSlider1.setMajorTickSpacing(1);
        jo_jSlider1.setMaximum(3);
        jo_jSlider1.setMinimum(1);
        jo_jSlider1.setPaintTicks(true);

        jo_jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jo_jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jo_jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jo_jLabel2.setText("włączyć tryb rankingowy");

        jo_jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jo_jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jo_jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jo_jLabel3.setText("średni ");

        jo_jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jo_jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jo_jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jo_jLabel4.setText("trudny");

        jo_jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jo_jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jo_jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jo_jLabel6.setText("Gra Komputerowa");

        jo_jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jo_jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jo_jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jo_jLabel7.setText("wybierz postać");

        jo_jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "wojownik", "mag", "łucznik" }));

        jo_jLabel8.setBackground(new java.awt.Color(255, 255, 0));
        jo_jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jo_jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jo_jLabel8.setText("tródność przeciwników");

        jo_jToggleButton1.setText("nierankingowy");

        jo_jToggleButton2.setText("rankingowy");
        jo_jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jToggleButton2ActionPerformed(evt);
            }
        });

        jo_jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\lawio\\Desktop\\liga.png")); // NOI18N

        jo_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jo_jPanel1Layout = new javax.swing.GroupLayout(jo_jPanel1);
        jo_jPanel1.setLayout(jo_jPanel1Layout);
        jo_jPanel1Layout.setHorizontalGroup(
            jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jo_jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jo_jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jo_jLabel6))
                    .addGroup(jo_jPanel1Layout.createSequentialGroup()
                        .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jo_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jo_jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jo_jPanel1Layout.createSequentialGroup()
                                .addComponent(jo_jLabel8)
                                .addGap(20, 20, 20))
                            .addComponent(jo_jSlider1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jo_jPanel1Layout.createSequentialGroup()
                                .addComponent(jo_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jo_jLabel3)
                                .addGap(52, 52, 52)
                                .addComponent(jo_jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jo_jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jo_jLabel9))
                    .addGroup(jo_jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jo_jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jo_jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jo_jTextField1)
                            .addGroup(jo_jPanel1Layout.createSequentialGroup()
                                .addComponent(jo_jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(jo_jToggleButton1)))
                        .addGap(91, 91, 91))))
        );
        jo_jPanel1Layout.setVerticalGroup(
            jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jo_jPanel1Layout.createSequentialGroup()
                .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jo_jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jo_jLabel6))
                    .addComponent(jo_jLabel9))
                .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jo_jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jo_jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jo_jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jo_jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jo_jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jo_jToggleButton2)
                        .addComponent(jo_jToggleButton1))
                    .addComponent(jo_jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jo_jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jo_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jo_jLabel4)
                    .addComponent(jo_jLabel3)
                    .addComponent(jo_jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jo_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jo_jMenu1.setText("plik");

        jMenuItem1.setText("zapisz");
        jo_jMenu1.add(jMenuItem1);

        jMenuItem2.setText("wczytaj");
        jo_jMenu1.add(jMenuItem2);

        jMenuItem3.setText("zamknij");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jo_jMenu1.add(jMenuItem3);

        jo_jMenuBar.add(jo_jMenu1);

        jo_jMenu2.setText("Edit");

        jMenuItem4.setText("zmień czcionke");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jo_jMenu2.add(jMenuItem4);

        jMenuItem5.setText("zmień tło");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jo_jMenu2.add(jMenuItem5);

        jo_jMenuBar.add(jo_jMenu2);

        jo_jMenu3.setText("o programie");

        jo_MenuItem7.setText("o programie");
        jo_jMenu3.add(jo_MenuItem7);

        jo_jMenuItem8.setText("help");
        jo_jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jMenuItem8ActionPerformed(evt);
            }
        });
        jo_jMenu3.add(jo_jMenuItem8);

        jo_jMenuBar.add(jo_jMenu3);

        setJMenuBar(jo_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jo_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jo_jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jo_jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jo_jMenuItem8ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jo_jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jo_jToggleButton2ActionPerformed

    private void jo_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jo_jTextField1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
   
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wlasnyprojekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wlasnyprojekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wlasnyprojekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wlasnyprojekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new wlasnyprojekt().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jo_MenuItem7;
    private javax.swing.JComboBox<String> jo_jComboBox1;
    private javax.swing.JLabel jo_jLabel1;
    private javax.swing.JLabel jo_jLabel2;
    private javax.swing.JLabel jo_jLabel3;
    private javax.swing.JLabel jo_jLabel4;
    private javax.swing.JLabel jo_jLabel6;
    private javax.swing.JLabel jo_jLabel7;
    private javax.swing.JLabel jo_jLabel8;
    private javax.swing.JLabel jo_jLabel9;
    private javax.swing.JMenu jo_jMenu1;
    private javax.swing.JMenu jo_jMenu2;
    private javax.swing.JMenu jo_jMenu3;
    private javax.swing.JMenuBar jo_jMenuBar;
    private javax.swing.JMenuItem jo_jMenuItem8;
    private javax.swing.JPanel jo_jPanel1;
    private javax.swing.JSlider jo_jSlider1;
    private javax.swing.JTextField jo_jTextField1;
    private javax.swing.JToggleButton jo_jToggleButton1;
    private javax.swing.JToggleButton jo_jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
